#datasource specific configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/masterdb
    username: root
    password: root

#jpa
  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: update
      
      